// Verifies the locale bundles against the generated English bundle.
//
// The English bundle (l10n/bundle.l10n.json) is generated by
// `vscode-l10n-dev export`. Each locale bundle must:
//   1. contain no stale keys (a key not present in English)
//   2. translate every English key (report missing ones)
//   3. preserve every {0}/{1}... placeholder from the English source
//
// Exit code is non-zero if any locale fails, so this doubles as a CI gate.

const fs = require("fs");
const path = require("path");

const L10N_DIR = path.join(__dirname, "..", "l10n");
const EN_FILE = "bundle.l10n.json";

function read(file) {
  return JSON.parse(fs.readFileSync(path.join(L10N_DIR, file), "utf8"));
}

/** Set of placeholders like {0}, {1} used in a message. */
function placeholders(str) {
  return new Set(str.match(/\{\d+\}/g) ?? []);
}

const en = read(EN_FILE);
const enKeys = Object.keys(en);

const locales = fs.readdirSync(L10N_DIR).filter((f) => /^bundle\.l10n\..+\.json$/.test(f));

let hasError = false;

for (const file of locales) {
  const loc = read(file);
  const locKeys = new Set(Object.keys(loc));
  const problems = [];

  // 1. stale keys — present in the locale but no longer in English
  for (const key of locKeys) {
    if (!(key in en)) {
      problems.push(`  stale (not in English): "${key}"`);
    }
  }

  // 2. missing translations — English keys absent from the locale
  const missing = enKeys.filter((key) => !locKeys.has(key));
  for (const key of missing) {
    problems.push(`  missing translation: "${key}"`);
  }

  // 3. placeholder integrity — {0}/{1} must survive translation
  for (const key of enKeys) {
    if (!locKeys.has(key)) {
      continue;
    }
    const want = placeholders(en[key]);
    const got = placeholders(loc[key]);
    for (const p of want) {
      if (!got.has(p)) {
        problems.push(`  placeholder ${p} dropped: "${key}"`);
      }
    }
    for (const p of got) {
      if (!want.has(p)) {
        problems.push(`  placeholder ${p} added: "${key}"`);
      }
    }
  }

  if (problems.length > 0) {
    hasError = true;
    console.error(`✗ ${file}`);
    for (const p of problems) {
      console.error(p);
    }
  } else {
    console.log(`✓ ${file} (${locKeys.size}/${enKeys.length} translated)`);
  }
}

if (hasError) {
  process.exitCode = 1;
  console.error("\nl10n check failed.");
}
